### PR TITLE
fix(perceptual-speed-index): use proper SSIM options

### LINKED ISSUE #41: image-ssim call is borked
I have a PR in progress to fix, but basically the issue is https://github.com/pmdartus/speedline/blob/master/src/speed-index.js#L50 interacting with https://github.com/darosh/image-ssim-js/blob/master/index.ts#L155. The image being read to determine SSIM is not the actual image because it's being interpreted in pixel-sets of 3 when the encoding is pixel-sets of 4 with the 4th being the alpha channel which is always 1.

### PR DESCRIPTION
**Pull request by patrickhulce**
fixes #41

### CODE REVIEW

File: test/speed-index.js [hunk 1]
```diff
@@ -44,6 +44,30 @@ test('visual progress should have 0 and 100 for different images', async t => {
 	t.is(data.frames[1].getProgress(), 100);
 });
 
+test('perceptual progress should use SSIM', async t => {
```
Comment (paulirish) [inline test/speed-index.js:59]: do you want to also add a more narrow test of `calculateFrameSimilarity`? we could then manually verify that calculateFrameSimilarity says the same thing as http://darosh.github.io/image-ssim-js/test/browser_test.html :)

File: test/speed-index.js [hunk 2]
```diff
@@ -88,7 +112,16 @@ test('speed indexes calculated for 3 frame (blank @1s, content @2s, more content
 	speedIndex.calculatePerceptualProgress(data.frames);
 	const indexes = speedIndex.calculateSpeedIndexes(data.frames, data);
 	t.is(Math.floor(indexes.speedIndex), 2040);
-	t.is(Math.floor(indexes.perceptualSpeedIndex), 2066);
+	t.is(Math.floor(indexes.perceptualSpeedIndex), 2030);
+});
+
+test('speed indexes calculated for realistic trace', async t => {
+	const data = await frame.extractFramesFromTimeline('./assets/progressive-app-updated.json');
```
Comment (paulirish) [inline test/speed-index.js]: how about progressive-app-m59.json ?

File: test/speed-index.js (hunk 1 above)
Comment (patrickhulce) [reply test/speed-index.js:59]: done

File: test/speed-index.js (hunk 2 above)
Comment (patrickhulce) [reply test/speed-index.js]: yeah good call, I realized "updated" makes no sense outside of this commit haha, done

File: test/speed-index.js [hunk 3]
```diff
@@ -18,6 +18,16 @@ function calculateVisualProgressFromImages(images = [], delay = 1000) {
...
 }
 
+test('frame similarity should reflect SSIM', async t => {
+	const data = calculateVisualProgressFromImages([
+		'./assets/frameA.jpg',
+		'./assets/frameC.jpg'
+	]);
+
+	const similarity = speedIndex.calculateFrameSimilarity(data.frames[0], data.frames[1]);
+	t.is(Math.floor(similarity * 100), 78);
```
Comment (paulirish) [inline test/speed-index.js:28]: i was able to repro this number on http://darosh.github.io/image-ssim-js/test/browser_test.html with some hacks

the scaling they do on the canvas totally fucks up the numbers. (i end up with 75 instead of 78)
But..  if you breakpoint on `var canvas = document.createElement('canvas');` (inside the img.onload handler) and run the following for the two times it pauses, we get a matching number (.787): 

```js
width = img.width; height = img.height;
```

screenshot: 
image

File: test/speed-index.js [hunk 4]
```diff
@@ -18,6 +18,18 @@ function calculateVisualProgressFromImages(images = [], delay = 1000) {
...
+	// You should be able to reproduce this result (78) on http://darosh.github.io/image-ssim-js/test/browser_test.html
```
Comment (paulirish) [inline test/speed-index.js:29]: I added this little comment about reproducibility. ;)

**Review by paulirish — APPROVED** [review]
